// flow-typed signature: 69e21fdf7f2dc1b28dc16a25d43abd72
// flow-typed version: <<STUB>>/react-no-ssr_v^1.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-no-ssr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-no-ssr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-no-ssr/dist/index' {
  declare module.exports: any;
}

declare module 'react-no-ssr/scripts/mocha_runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-no-ssr/dist/index.js' {
  declare module.exports: $Exports<'react-no-ssr/dist/index'>;
}
declare module 'react-no-ssr/index' {
  declare module.exports: $Exports<'react-no-ssr'>;
}
declare module 'react-no-ssr/index.js' {
  declare module.exports: $Exports<'react-no-ssr'>;
}
declare module 'react-no-ssr/scripts/mocha_runner.js' {
  declare module.exports: $Exports<'react-no-ssr/scripts/mocha_runner'>;
}
